[package]
name = "raffi"
description = "A simple wofi launcher based on YAML file"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
walkdir = "2.3.2"
